### ISSUE TITLE
Refelktion der UV-Strahlung im Rohr

### ISSUE THREAD

**Issue by stockh0lm** [teutronic-gmbh/corona-killer#2]
Wenn ich den Aufbau richtig verstehe ist das Rohr ein normales KG-Rohr, gell? In der Rechnung wird davon ausgegangen, dass das UV-Licht an der Oberfläche des Rohres (verlustfrei) gespiegelt wird. 

- ist das KG-Rohr UV-stabil? KG-Rohre die ich an der Sonne sehe verfärben sich. 
- für die Luftsterilisation ist es wichtig, dass möglichst viel der UV-Strahlung von der Wand zurückreflektiert wird. Ist das der Fall? kann man das Innere der Röhre sonst vielleicht mit Alufolie auskleiden oder ein Metallrohr nehmen?

**Comment by teutronic-gmbh** [comment]
Ich hab da tatsächlich Alufolie verklebt wie sie zum Tapezieren verwendet wird. Die hat eine Rückseite mit Papier. Beim ersten Mal habe ich das ganz zum Schluss gemacht und überall mit dem Kleber rumgesaut. Das muss zu einem früheren Zeitpunkt des Zusammenbaus passieren. Daran feile ich noch  :-)

**Comment by stockh0lm** [comment]
I read the mirror sheeting i am going to put in (or even the aluminium of a pipe reflects around 90% of the UV radiation back. That value is important to know for further simulation or calculation of the effective radiation intensity in the pipe.
